import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
    ru: {
        translation: {
            sarlavha: "Клиника Фатхулла Ота Мед",
            text1: "Предоставление населению комплексных медицинских услуг: консультации специалистов всех направлений и поликлиническое лечение, медицинские осмотры и диагностические процедуры.",
            button1: "Записаться на прием",
            sarlavha2: "Популярные ",
            sarlavha3: " услуги",
            text2: " Оставьте заявку и мы свяжемся с вами в ближайшее время",
            ism: "Ваше имя",
            tel: "Ваш телефон",
            tanla: "Выберите услуги",
            roziman: "Я согласен с политикой конфиденциальности.",
            zayavka: " Оставить заявку",
            azgina: "Немного",
            malumot: "о нашем медицинском центре",
            text3: "В нашей клинике проводится диагностика заболеваний с использованием самого современного оборудования. Проводятся комплексные анализы и обследования по различным направлениям, консультации специалистов, углубленное изучение состояния пациента и индивидуальный подход.Созданы все условия для комфорта и покоя пациентов. ",
            malumot1: "лет заботы о вашем здоровье",
            malumot2: "Опытные специалисты",
            malumot3: "медицинских услуг по всем направлениям",
            malumot4: "Приём к врачу в день обращения",
            kun: "День в день",
            dok1: "Джалилова Шахноза Патхиллаевна",
            dok2: "Доктор Бахром — Нутрициолог",
            dok3: "Акбарова Наргиза Патхиллаевна",
            dok4: "Ахмеджанова Рашида Ахатовна ",
            button2: " Нажмите для информации",
            button3: "Закрыть",
            info1: "Выявление, определение, оценка, обнаружение, диагностика, лечение, профилактика: врожденных аномалий(дисплазии тазобедренного сустава, вывихи, подвывихи, косолапости, кривошея) искривления позвоночника(сколиоз, кифоз, лордоз) плоскостопия и других деформаций стоп последствий травм(переломы, растяжения, вывихи) боль и ограничения в суставах устойчивые хронические боли в конечностях, позвоночнике, суставах при артрозе остеохондрозе Электропунктурная диагностика по методу Фолля: выявление патологии сердечно - сосудистой, дыхательной, эндокринной, нервной, пищеварительной, мочеполовой систем определение наследственной предрасположенности к заболеваниям оценка иммунной реактивности подборка и тестирование лекарственных препаратов диагностирование онкологических заболеваний определение степени загрязнения организма вредными веществами выявление скрытых аллергических реакций проведение анализа эффективности лечения Инфракрасная керамическая резонансная терапия: являясь совершенно безвредной для организма, инфракрасные керамические излучатели обладают избирательным воздействием только на патологически измененные органы и ткани нормализуя обменные процессы на молекулярном уровне, они устраняют причину болезни, а не только её симптомы инфракрасные излучатели применяются для лечения и профилактики иммунных, эндокринных, острых и хронических соматических, инфекционных, вирусных, онкологических и других заболеваний реабилитация после травм и операций(ускорение восстановления) снятие мышечных спазмов и улучшение подвижности расслабляющие процедуры для снятия усталости и стресса уход за кожей и борьба с целлюлитом(улучшение обменных процессов) профилактика хронических заболеваний опорно - двигательного аппарата ",
            info2: "Я лечу все виды заболеваний у людей на основе их биоэнергетики. Я лечу многие женские миомы, кистозные заболевания, цирроз печени, виды гепатита, гормональные нарушения, диабет, психические состояния людей и многие другие заболевания.",
            info3: "Профессиональные навыки  :Оказание помощи при заболевании сосудов сердца и головного мозга : гипертонии, сахарный диабет ,последствия сотрясение мозга.  Заболевания  нервной  системы, бессоница ,синдром хронической усталости, головокружение  шум в ушах. Заболевание ЖКТ гастрит  колит ,геморрой. Генекологические и урологические заболевания : хронический простатит , гиперплазия  представленной железы . Аменорея воспаление таковых органов ,воспаление , климактерический  синдром . Ушибы ,вывихи переломы .ревматизм ног и др. Курс процедур Биоэнерго Регуляции рекомендован при недостаточной микроциркуляции крови в конечностей онемение и потеря чувствительности . Болях составные мышечные головные приступы мигрени обострении остеохондроз.  Затруднение дыхания : пневмонии и постковидный синдром ,сложные формы бронхит. Нарушение тонуса мышц после травм , инсультов .Проявление возрастных изменений.",
            vrach: "Спецаилисти",
            vrach2: "нашей клиники",
            otzivi1: "Отзывы ",
            otzivi2: "пациентов",
            otziv1: "Попала Шахноза Патхиллаевна.Oчень довольна приёмом и проведением ультразвуковой диагностики. Спасибо за внимательное отношение к пациентам При возникнвении проблем теперь только к ней!",
            otziv2: "Огромное спасибо врачу за тщательное обследование. Выявили нехватку витамина Д, проблем с щитовидной, к счастью, не оказалось. Доктор приятная в общении и настоящий профессионал!",
            vrachs: "Врач:",
            karta1: "Как ",
            karta2: "нас найти",
            foot1: "Клиника Fathullo ota известна своим профессиональным подходом к лечению пациентов.",
            foot2: "© 2018-2024 Городской Медицинский Центр. Все права защищены.",
            foot3: "Телефон",
            foot4: "Ежедневно с 8.00 до 15.00",
            foot5: "Воскресенье закрыто",
            foot6: "Написать в Инстаграм",
            foot7: "Написать в Телеграм",
            foot8: "Записаться",
            navbar1: "О нас",
            navbar2: " Услуги",
            navbar3: "Врачи",
            navbar4: "Отзывы",
            navbar5: "Контакты",

        },
    },
    uz: {
        translation: {
            sarlavha: "Fatxulla Ota Med Klinikasi",
            text1: "Mijozlarga kompleks tibbiy xizmat ko`rsatish: barcha yo‘nalishlar bo‘yicha mutaxassislar maslahati va ambulator davolanish, tibbiy ko‘rik va diagnostika muolajalari.",
            button1: "Qabulga yozilish",
            sarlavha2: "Ommabop ",
            sarlavha3: "xizmatlar",
            text2: "Zayavka qoldiring va biz imkon qadar tezroq siz bilan bog'lanamiz",
            ism: "Ismingiz",
            tel: "Telefon raqamingiz",
            tanla: "Xizmatlarni tanlang",
            roziman: "Men maxfiylik siyosatiga roziman",
            zayavka: "So'rov qoldirish",
            azgina: "Bizning",
            malumot: "tibbiyot markazimiz haqida",
            text3: "Klinikamiz eng zamonaviy uskunalar yordamida kasalliklarni aniqlaydi, Turli sohalar bo `yicha kompleks tahlillar va tekshiruvlar amalga oshiriladi, mutaxassis maslahatlari, Bemorlarning holatini chuqur o‘ rganib chiqish va individual yondashuv.Bemorlarning qulayligi va xotirjamligi uchun barcha sharoitlar yaratilgan.",
            malumot1: "yil sog'lig'ingizga g'amxo'rlik",
            malumot2: "Tajribali mutaxassislar",
            malumot3: "xil sohalarda tibbiy xizmat",
            malumot4: "Davolanish kunida shifokor bilan uchrashuv",
            kun: "Kundan kunga",
            dok1: "Jalilova Shaxnoza Pathillayevna",
            dok2: "Doktor Bahrom — Nutriцiolog ",
            dok3: " Akbarova Nargiza Pathillayevna",
            dok4: "Axmedjonova Rashida Axatovna",
            button2: "Ma'lumot uchun bosing",
            button3: "Yopish",
            info1: "Aniqlash, baholash, tashxislash, davolash, oldini olish: tug`ma anomaliyalar(son displazi, dislokatsiyalar, subluksatsiyalar, to`p oyoq, tortikollis umurtqa pog `onasi egriligi (skolioz, kifoz, lordoz) tekis oyoqlar va boshqa oyoq deformatsiyalari jarohatlarning oqibatlari(sinishlar, burilishlar, dislokatsiyalar) qo`shma og'riqlar va cheklovlar artroz, osteoxondroz tufayli oyoq - qo'llarda, umurtqa pog'onasida, bo'g'imlarda doimiy surunkali og'riq Voll usuli yordamida elektroponktura diagnostikasi: yurak - qon tomir, nafas olish, endokrin, asab, ovqat hazm qilish va genitouriya tizimlarining patologiyalarini aniqlash kasalliklarga irsiy moyillikni aniqlash immun reaktivligini baholash dori vositalarini tanlash va sinovdan o'tkazish saraton kasalligini tashxislash organizmning zararli moddalar bilan ifloslanish darajasini aniqlash yashirin allergik reaktsiyalarni aniqlash davolash samaradorligini tahlil qilish Infraqizil keramik rezonans terapiyasi: Tana uchun mutlaqo zararsiz bo'lgan infraqizil keramik emitentlar faqat patologik o'zgargan organlar va to'qimalarga selektiv ta'sir ko'rsatadi metabolik jarayonlarni molekulyar darajada normallashtirish orqali ular nafaqat uning alomatlarini, balki kasallikning sababini ham yo'q qiladi, infraqizil emitentlar immun,endokrin, o'tkir va surunkali somatik, yuqumli, virusli, onkologik va boshqa kasalliklarni davolash va oldini olish uchun ishlatiladi. jarohatlar va operatsiyalardan keyin reabilitatsiya(tiklanishni tezlashtirish) mushaklarning spazmlarini yo'qotish va harakatchanlikni yaxshilash charchoq va stressni bartaraf etish uchun tinchlantiruvchi muolajalar terini parvarish qilish va selülitga qarshi kurash(metabolik jarayonlarni yaxshilash) mushak-skelet tizimining surunkali kasalliklarining oldini olish ",
            info2: "Men odamlardagi barcha turdagi kasalliklarni bioenergiyasiga qarab davolayman. Men ayollarning ko'plab miomalari, kistlar kasalliklari, jigar sirrozi, gepatit turlari, gormonal kasalliklar, diabet, odamlarning ruhiy holati va boshqa ko'plab kasalliklarni davolayman.",
            info3: "Kasbiy ko'nikmalar: Yurak va miya qon tomir kasalliklarida yordam ko'rsatish: gipertoniya, diabet, miya chayqalishining oqibatlari. Asab tizimining kasalliklari, uyqusizlik, surunkali charchoq sindromi, bosh aylanishi, tinnitus. Oshqozon-ichak kasalliklari gastrit kolit, hemoroid. Genekologik va urologik kasalliklar: surunkali prostatit, bezning giperplaziyasi. Amenoreya, bunday organlarning yallig'lanishi, yallig'lanish, menopauza sindromi. Ko'karishlar, dislokatsiyalar, sinishlar, oyoqlarning revmatizmi va boshqalar. Ekstremitalarda qon mikrosirkulyatsiyasining etarli emasligi, uyqusizlik va sezgirlikni yo'qotish uchun Bioenergo Regulation protseduralari kursi tavsiya etiladi. Og'riq, murakkab mushak bosh og'rig'i, migren, osteoxondrozning kuchayishi. Nafas olishda qiyinchilik: pnevmoniya va post-Covid sindromi, bronxitning murakkab shakllari. Jarohatlardan keyin mushaklarning ohangini buzish, yoshga bog'liq o'zgarishlarning namoyon bo'lishi.",
            vrach: "Klinikamizning",
            vrach2: "Mutaxasislari",
            otzivi1: "Bemorlarning  ",
            otzivi2: "sharhlari",
            otziv1: "Shaxnoza Patillaevnaga tushdim va ultratovush tekshiruvidan mamnunman. Bemorlarga ehtiyotkorlik bilan munosabatda bo'lganingiz uchun rahmat, agar muammolar yuzaga kelsa, endi faqat uning oldiga boring!",
            otziv2: "To'liq tekshiruv uchun shifokorga katta rahmat. Yaxshiyamki, D vitamini etishmovchiligi aniqlandi, qalqonsimon bez bilan bog'liq muammolar yo'q edi. Shifokor bilan suhbatlashish yoqimli va haqiqiy professional!",
            vrachs: "Vrach:",
            karta1: "Bizni",
            karta2: "qanday topishingiz mumkin",
            foot1: "Fathullo ota klinikasi bemorlarni davolashga professional yondashuvi bilan mashhur.",
            foot2: "© 2018-2024 Shahar tibbiyot markazi. Barcha huquqlar himoyalangan.",
            foot3: "Telefon",
            foot4: "Har kuni soat 8.00 dan 15.00 gacha",
            foot5: "Yakshanba yopiq",
            foot6: "Instagramga yozish",
            foot7: "Telegramga yozish",
            foot8: "Yozilish",
            navbar1: "Biz haqimizda",
            navbar2: " Xizmat Ko`rsatish",
            navbar3: "Vrachlar",
            navbar4: "Sharhlar",
            navbar5: "Bog`lanish",
        },
    },
};

i18n
    .use(initReactI18next)
    .init({
        resources,
        lng: "ru", // Default til
        fallbackLng: "ru", // Agar til topilmasa fallback
        interpolation: {
            escapeValue: false,
        },
    });

export default i18n;